name: Release

# Only trigger, when the build workflow succeeded
on: 
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    

    steps:
      - uses: actions/checkout@v3
      - name: Bump the version tag
        uses: paulhatch/semantic-version@v5.3.0
        with:
           major_pattern: "(major)"
           minor_pattern: "(minor)"





        

          
          
