name: Create Release

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pre-merge-label checks"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create release version
        uses: paulhatch/semantic-version@v5.3.0
        id: next-version
        with: 
          tag_prefix: "v"
          major_pattern: "(major)"
          minor_pattern: "(minor)"
      - name: print version to terminal
        run: |
          echo ${{ steps.next-version.outputs.version }}
          
          
