name: Release

# Only trigger, when the build workflow succeeded
on: 
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    

    steps:
      - uses: actions/checkout@v3
      - name: Check for the PR label
        id: label
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: major,minor,patch
      - name: Bump the version tag
        if: github.event.pull_request.merged == true
        id: next_version
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: ${{ steps.label.outputs.match }}
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: print version to terminal
        run: |
          echo v${{ steps.next_version.outputs.version }}
      - name: Create release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.next_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}


        

          
          
