# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

---

name: Labelling
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  prettier-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
        # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          only_changed: True
  auto-labeler:
    needs: prettier-action
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

  check-labels:
    needs: auto-labeler
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch,feature
          repo_token: ${{ secrets.GITHUB_TOKEN }}

