
---

name: Pre-merge
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  add-label:
    name: Add Label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

  check-labels:
    needs: add-label
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch,feature
          repo_token: ${{ secrets.GITHUB_TOKEN }}

