
---

name: Pre-merge
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  add-label:
    name: Add Label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

  check-labels:
    needs: add-label
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch,feature
          repo_token: ${{ secrets.GITHUB_TOKEN }}


  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.57.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npm run lint
      

      - name: Amend Commit 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit --amend --no-edit
          git log
          git push -f origin

  prettify-code:
    needs: check-labels
    name: Prettify Code
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: creyD/prettier_action@v4.3
        with:
        # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          only_changed: True

