name: Prettier

# Only trigger, when the build workflow succeeded
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
        # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          only_changed: True
